[package]
name = "r2d2_sqlite"
version = "0.1.2"
authors = ["Jovansonlee Cesar<ivanceras@gmail.com>"]
license = "MIT"
description = "Sqlite support for the r2d2 connection pool"
repository = "https://github.com/ivanceras/r2d2-sqlite"
documentation = "http://ivanceras.github.io/r2d2-sqlite/r2d2_sqlite/"
keywords = ["sqlite", "r2d2", "pool"]

[lib]
name = "r2d2_sqlite"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
r2d2 = "0.7"
rusqlite = "0.10"

[dev-dependencies]
tempdir = "0.3"
